# Config file for travis-ci.org

language: php
php:
  - "7.4"
  - "7.3"
  - "7.2"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
before_install: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
install: sh travis.sh
script: cd _test && phpunit --stderr --group plugin_instantpage
